### PR TITLE
Text panel split padding

### PR DESCRIPTION
**Pull request by Froloket64**
**Breaking change**
Allows more control over padding for `TextPanel` - now separate for each axis.

There's also a design to make it non-breaking, but that will make it more ugly (adding `padding_y`, `padding_x` as parameters instead if changing `padding` and having 3 of them, which would need to be applied in some non-conflicting way to `self._padding`). But if you think it's worth it, I can tackle with that.
Although, since `TextPanel` was introduced very recently, everyone who started using it probably tries to keep up with changes anyways, so mb we can get away with it.

### CODE REVIEW

**Comment by salt-die** [comment]
Let's do `padding_y`, `padding_x`.  I think we should clamp these values to be non-negative as well.

**Comment by Froloket64** [comment]
Also, can I ask, why did you decide to put `y` as the first axis in the library? It feels very confusing since the convention is `x` then `y`

**Comment by salt-die** [comment]
When you index a 2-d numpy array, say :
```py
[
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
]
```
The first index will select the row (moving vertically) and the second will select the column. So I used this convention for the entire library so that one could use pos to directly index the underlying arrays if one wanted.  (y, x) is also a curses convention so it seems fitting for a terminal library.

**Comment by Froloket64** [comment]
Aah, thanks for the explanation, that makes sense

**Comment by Froloket64** [comment]
Should be good now

**Comment by salt-die** [comment]
Remove `padding` altogether. Just `padding_x` /`padding_y` is good enough. This will be similar to `GridLayout`'s padding arguments.

**Comment by Froloket64** [comment]
Oh, but what's the point of using `padding_x`, `padding_y` then? I thought `padding` alone as a tuple would be much cleaner. If we're not concerned with breaking compat

**Comment by salt-die** [comment]
Yeah, I may add a `tuple[int, int, int, int]` data structure at some point for padding if any more widgets pop up that use it. But until then, just separate int attributes is fine.

**Comment by Froloket64** [comment]
But wouldn't that be better to set up the foundation for the new such widgets **now** rather than breaking all the current ones sometime later

**Comment by Froloket64** [comment]
Also, do we really need individual top, right, bottom and left paddings? I feel like that's excessive. `x` and `y` should be enough. _But not feeling too strong on that either_

**Comment by salt-die** [comment]
No, not for this widget. If I made a `Padding` data structure, this widget would use it, but until then I think two padding attributes is plenty.

**Comment by Froloket64** [comment]
Ok, I'll remove the `padding` then.
Also, am I getting it right, that you want both the parameter and the attribute removed?

**Comment by salt-die** [comment]
Yep.

**Comment by Froloket64** [comment]
Done

**Pull request merged**
