### PR TITLE
Text container

### PR DESCRIPTION
**Pull request by Froloket64**
Solve #8.

The name was the first thing that came to mind, but I think it's fitting with the others.
Not sure if I did this right, but it seems to be working (except there's strange theming going on)

### CODE REVIEW

**Comment by salt-die** [comment]
Inherit `TextWidget` (to have access to `add_border`) and add optional padding (I think this would require an extra nested widget container).
Also would like it to be multi-line. Maybe single-line as an optional parameter?
Would like to give this it's own color pair in the `ColorTheme`, say, `text_panel` and rename the class to `TextPanel`.

Similar to:
```py
class TextPanel(Themable, TextWidget):
    def __init__(self, *, padding=1, multiline=True, **kwargs):
        self._inner = Widget()
        self._text = TextWidget()
        self._inner.add_widget(self._text)
        self.add_widget(self._inner)
       ...
```
visually:
```
+-----------------+
|     padding     |
|   +---------+   |
| p |         | p | 
| a |  inner  | a |
| d |         | d |
|   +---------+   |
|     padding     |
+-----------------+
```
Where `_inner` is pretty much what you already have.

**Comment by Froloket64** [comment]
Ok, trying to add the theming here, but I encountered this strange behavior. When I add this snippet _(below)_ to the `TextContainer`/`TextPanel` code, I paints it correctly, with the weird red-ish and dark blue-ish background, as set in `DEFAULT_COLOR_THEME`. However, `Textbox`, using the same code has the white-on-blue look that matches the look of other elements. Can you show me where I get things wrong?
`TextContainer`: https://github.com/Froloket64/nurses_2/blob/7f01e83ebf8552ca934063ec8cf0f3cad3859a7d/nurses_2/widgets/text_container.py#L193-L197
`Textbox`: https://github.com/Froloket64/nurses_2/blob/7f01e83ebf8552ca934063ec8cf0f3cad3859a7d/nurses_2/widgets/textbox.py#L254-L258

**Comment by salt-die** [comment]
I'm not sure why the color theming is off, but managing the cursor and related methods shouldn't be necessary since it's not an input widget.

**Comment by salt-die** [comment]
I went ahead and added a `TextPanel`. Hope this works for you!

**Pull request closed without merging**
